### ISSUE TITLE
Greeter?

### ISSUE THREAD

**Issue by jgrossberg** [RobEstis/webserver#2]
Hey can you implement a new Greet feature where if someone makes a GET request to a greet endpoint with a "name" parameter, a greeting is returned for that name? 

Like for example:

```
GET localhost:8000/greet/jonah 
returns Hello jonah, thank you for using this webserver
```

If you are ok with that, lets just start by creating a class called `GreetingService.js` and give it a single function `greet(name)` that returns a string. We can wire it up using a controller after the class is created and tested!

**Comment by RobEstis** [comment]
Greeter has been and added to the new-branch.
